image: Visual Studio 2019

build_script:
- ps: |
    msbuild /t:Build /restore /v:minimal /p:Configuration=Release
    msbuild ReflectionAnalyzers /t:Pack /p:NoBuild=true /p:PackageOutputPath=..\publish /p:Configuration=Release

on_success:
- ps: Get-ChildItem publish\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
